/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCardList: typeof import('./../components/baseCardList/baseCardList.vue')['default']
    BaseCesium: typeof import('./../components/baseCesium/BaseCesium.vue')['default']
    BaseChart: typeof import('./../components/baseChart/BaseChart.vue')['default']
    BaseMenu: typeof import('./../components/baseMenu/baseMenu.vue')['default']
    BaseMenuHorizontalAside: typeof import('./../components/baseMenu/baseMenuHorizontalAside.vue')['default']
    BaseMenuHorizontalHeader: typeof import('./../components/admin/baseMenuHorizontal/baseMenuHorizontalHeader.vue')['default']
    BaseOverlay: typeof import('./../components/baseOverlay/baseOverlay.vue')['default']
    BasePanelCard: typeof import('./../components/basePanel/basePanelCard.vue')['default']
    BasePanelMask: typeof import('./../components/basePanel/basePanelMask.vue')['default']
    BasePanelTitle: typeof import('./../components/basePanel/basePanelTitle.vue')['default']
    copy: typeof import('./../components/basePanel/basePanelMask copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenFooter: typeof import('./../components/screen/ScreenFooter.vue')['default']
    ScreenLayout: typeof import('./../components/screen/ScreenLayout.vue')['default']
  }
}
