/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCardList: typeof import('./../components/baseCardList/baseCardList.vue')['default']
    BaseCesium: typeof import('./../components/baseCesium/BaseCesium.vue')['default']
    BaseChart: typeof import('./../components/baseChart/BaseChart.vue')['default']
    BaseDialog: typeof import('./../components/baseDialog/baseDialog.vue')['default']
    BaseMenu: typeof import('./../components/baseMenu/baseMenu.vue')['default']
    BaseMenuHorizontalAside: typeof import('./../components/baseMenu/baseMenuHorizontalAside.vue')['default']
    BaseOverlay: typeof import('./../components/baseOverlay/baseOverlay.vue')['default']
    BasePagination: typeof import('./../components/base-pagination/base-pagination.vue')['default']
    BasePanelCard: typeof import('./../components/basePanel/basePanelCard.vue')['default']
    BasePanelMask: typeof import('./../components/basePanel/basePanelMask.vue')['default']
    BasePanelTitle: typeof import('./../components/basePanel/basePanelTitle.vue')['default']
    BasePopover: typeof import('./../components/basePopover/basePopover.vue')['default']
    BaseSectionTitle: typeof import('./../components/baseSectionTitle/baseSectionTitle.vue')['default']
    BaseStatList: typeof import('./../components/baseStatList/baseStatList.vue')['default']
    BaseTab: typeof import('./../components/baseTab/baseTab.vue')['default']
    BaseTable: typeof import('./../components/baseTable/baseTable.vue')['default']
    CameraPopup: typeof import('./../components/screen/popups/CameraPopup.vue')['default']
    ConfirmBox: typeof import('./../components/baseMessageBox/confirmBox.vue')['default']
    DeviceInfo: typeof import('./../components/screen/popups/DeviceInfo.vue')['default']
    DeviceStatusTag: typeof import('./../components/screen/popups/DeviceStatusTag.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FiberPopup: typeof import('./../components/screen/popups/FiberPopup.vue')['default']
    LayerControl: typeof import('./../components/screen/layerControl/layerControl.vue')['default']
    MapPopupPanel: typeof import('./../components/screen/mapPopup/MapPopupPanel.vue')['default']
    NestPopup: typeof import('./../components/screen/popups/NestPopup.vue')['default']
    PopupInfo: typeof import('./../components/screen/popups/PopupInfo.vue')['default']
    PopupPanel: typeof import('./../components/screen/mapPopup/popupPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteButton: typeof import('./../components/screen/siteSwitch/siteButton.vue')['default']
    SiteSwitch: typeof import('./../components/screen/siteSwitch/siteSwitch.vue')['default']
  }
}
