/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCesium: typeof import('./../components/screen/baseCesium/BaseCesium.vue')['default']
    BaseMenu: typeof import('./../components/screen/BaseMenu.vue')['default']
    BaseMenuHorizontalAside: typeof import('./../components/admin/baseMenuHorizontal/baseMenuHorizontalAside.vue')['default']
    BaseMenuHorizontalHeader: typeof import('./../components/admin/baseMenuHorizontal/baseMenuHorizontalHeader.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenFooter: typeof import('./../components/screen/ScreenFooter.vue')['default']
    ScreenLayout: typeof import('./../components/screen/ScreenLayout.vue')['default']
  }
}
